name: smart_pots_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 700
